name: CI (scan)
on: [pull_request]

permissions:
  contents: read
  pull-requests: read  # gitleaks precisa ler o PR
  # opcional: security-events: write (se enviar resultados para o Security tab)

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks (scan PR)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: IaC Security (tfsec)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: infra
