name: Release ML Artifacts

on:
  push:
    tags: [ "v*.*.*" ]

env:
  MODEL_NAME: mobilenetv2
  ARTIFACTS_BUCKET: ml-artifacts-048153623156
  AWS_REGION: us-east-1
  CDN_DOMAIN: d1y8lqisovngwq.cloudfront.net

permissions:
  contents: read
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version:           ${{ steps.v.outputs.version }}
      trained_artifact:  ${{ steps.names.outputs.trained_artifact }}
      labels_artifact:   ${{ steps.names.outputs.labels_artifact }}
      out_artifact:      ${{ steps.names.outputs.out_artifact }}
      venv_artifact:     ${{ steps.names.outputs.venv_artifact }}
    steps:
      - uses: actions/checkout@v4

      - name: Version from tag
        id: v
        run: echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      - name: Make artifact names
        id: names
        run: |
          echo "trained_artifact=trained-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          echo "labels_artifact=labels-${GITHUB_SHA}"   >> "$GITHUB_OUTPUT"
          echo "out_artifact=out-${GITHUB_SHA}"         >> "$GITHUB_OUTPUT"
          echo "venv_artifact=venv-${GITHUB_SHA}"       >> "$GITHUB_OUTPUT"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create venv and install deps (once)
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # se precisar de TF/CoreML:
          # pip install tensorflow==2.16.1 coremltools==7.2

      - name: Pack venv
        run: tar -czf venv.tar.gz .venv

      - name: Upload venv artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.names.outputs.venv_artifact }}
          path: venv.tar.gz
          retention-days: 7

  train:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Download venv
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.prepare.outputs.venv_artifact }}
          path: .

      - name: Extract venv
        run: tar -xzf venv.tar.gz

      - name: Train model
        run: |
          . .venv/bin/activate
          python -m scripts.train
          test -f models/trained/model_trained.h5
          test -f models/trained/model_labels.txt

      - name: Upload trained model (.h5)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.prepare.outputs.trained_artifact }}
          path: models/trained/model_trained.h5
          if-no-files-found: error
          retention-days: 7

      - name: Upload labels (.txt)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.prepare.outputs.labels_artifact }}
          path: models/trained/model_labels.txt
          if-no-files-found: error
          retention-days: 7

  test:
    runs-on: ubuntu-latest
    needs: [prepare, train]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Download venv
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.prepare.outputs.venv_artifact }}
          path: .

      - name: Extract venv
        run: tar -xzf venv.tar.gz

      - name: Download trained model
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.prepare.outputs.trained_artifact }}
          path: models/trained

      - name: Download labels
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.prepare.outputs.labels_artifact }}
          path: models/trained

      - name: Run inference tests
        run: |
          . .venv/bin/activate
          ls -la models/trained
          python -m scripts.test_inference \
            --model models/trained/model_trained.h5 \
            --labels models/trained/model_labels.txt

  convert:
    runs-on: ubuntu-latest
    needs: [prepare, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Download venv
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.prepare.outputs.venv_artifact }}
          path: .

      - name: Extract venv
        run: tar -xzf venv.tar.gz

      - name: Download trained model + labels
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.prepare.outputs.trained_artifact }}
          path: models/trained
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.prepare.outputs.labels_artifact }}
          path: models/trained

      - name: Convert to Android (.tflite) and iOS (.mlpackage)
        run: |
          . .venv/bin/activate
          python -m scripts.convert
          test -f models/artifactory/android/model.tflite
          test -d models/artifactory/ios/Model.mlpackage

      - name: Assemble versioned release folder
        run: |
          mkdir -p out/${{ needs.prepare.outputs.version }}/Android
          mkdir -p out/${{ needs.prepare.outputs.version }}/iOS

          cp models/trained/model_trained.h5             out/${{ needs.prepare.outputs.version }}/model.h5
          cp models/trained/model_labels.txt             out/${{ needs.prepare.outputs.version }}/labels.txt
          cp models/artifactory/android/model.tflite     out/${{ needs.prepare.outputs.version }}/Android/model.tflite
          cp -R models/artifactory/ios/Model.mlpackage   out/${{ needs.prepare.outputs.version }}/iOS/Model.mlpackage

          tree -a out || find out -maxdepth 3 -type f -print

      - name: Upload assembled 'out' artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.prepare.outputs.out_artifact }}
          path: out/**
          if-no-files-found: error
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: [prepare, convert]
    environment: production
    steps:
      - name: Download assembled 'out' artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.prepare.outputs.out_artifact }}
          path: out

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::048153623156:role/github-ml-artifacts-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp "out/${{ needs.prepare.outputs.version }}/" \
            "s3://${ARTIFACTS_BUCKET}/${MODEL_NAME}/${{ needs.prepare.outputs.version }}/" \
            --recursive --only-show-errors
